### ISSUE TITLE
[Feature Request] Comments before options

### ISSUE THREAD

**Issue by itsfolf** [Skyost/Skyoconfig#1]
Is possible to add a feature do use comments in options like this:

```
# this is the normal header
# with multiple lines
configuration:
# The basic options of the config
  simple_options:
    'option1': "something"
    'option2': "other thing"
  other:
# the location of spawn
    loc:
      'x': 5
      'y': 68
      'z': 50
#another random thing
    random:
       '1': "IDK"
```
